version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017" # Porta padrão do MongoDB
    environment:
      MONGO_INITDB_ROOT_USERNAME: projeto
      MONGO_INITDB_ROOT_PASSWORD: projeto
    volumes:
      - ./data:/data/db # Armazenamento de dados do MongoDB