version: '3'
services:
  app:
    image: node:14 # Use a imagem do Node.js que você preferir
    container_name: node_app
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - "3000:3000" # Porta em que a sua aplicação Node.js estará rodando
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017" # Porta padrão do MongoDB
    environment:
      MONGO_INITDB_ROOT_USERNAME: projeto
      MONGO_INITDB_ROOT_PASSWORD: projeto
    volumes:
      - ./data:/data/db # Armazenamento de dados do MongoDB